# GitHub Actions Workflow für Poetry + Python ML Pipeline
name: setup-poetry-environment

on:
  workflow_dispatch:
  issues:
    types: [assigned]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Install spaCy German Model
        run: |
          poetry run python -m spacy download de_core_news_sm

      - name: Setup ChromaDB Directory
        run: |
          mkdir -p data/vectors
          chmod 755 data/vectors

      - name: Install System Dependencies (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-deu
          sudo apt-get install -y poppler-utils

      - name: Verify Installation
        run: |
          poetry run python --version
          poetry run python -c "import spacy; nlp = spacy.load('de_core_news_sm'); print('spaCy German model loaded successfully')"
          poetry run python -c "import docling; print('Docling available')"
          poetry run python -c "import chromadb; print('ChromaDB available')"

      - name: Run Basic Health Check
        run: |
          poetry run python -c "
          from src.config import get_config
          config = get_config()
          print(f'Config loaded: {config.environment}')
          "

      - name: Setup Test Environment
        run: |
          poetry run pytest --collect-only tests/ || echo 'Test collection completed'
