custom_settings: {}
database:
  host: localhost
  name: llkjj_ml
  password: ''
  port: 5432
  ssl_mode: prefer
  user: llkjj_ml
debug: false
environment: production
logging:
  backup_count: 10
  enable_console: true
  enable_file: true
  level: WARNING
  max_file_size_mb: 10
  structured_logging: true
ml:
  batch_size: 32
  cpu_threads: 4
  gpu_enabled: false
  memory_limit_gb: 8
  model_cache_size: 1000
  timeout_seconds: 300
security:
  allowed_file_types:
  - pdf
  api_rate_limit: 1000
  enable_encryption: true
  max_upload_size_mb: 50
  session_timeout_minutes: 30
