# SKR03 Elektrohandwerk Mapping (MOVED from config.py)
# Korrigierte Konten für deutsche Elektrotechnik-Handwerk UG

wareneingang:
  elektromaterial: "3400"  # Wareneingang 19% Vorsteuer
  kabel: "3400"
  schalter: "3400"
  steckdosen: "3400"
  lampen: "3400"
  leuchten: "3400"
  sicherungen: "3400"
  installation: "3400"
  verbrauchsmaterial: "3400"

werkzeuge:
  werkzeuge_klein: "4985"  # Werkzeuge und Kleingeräte (Sofortaufwand)
  handwerkzeug: "4985"
  messgeraete_klein: "4985"

anlagegueter:  # über 800€
  maschinen: "0210"  # Maschinen
  bohrmaschinen: "0210"
  saegen: "0210"
  werkzeuge_gross: "0440"  # Werkzeuge (aktivierungspflichtig)
  anlagen: "0200"  # Technische Anlagen

betriebsausstattung:
  bueroausstattung: "0400"  # Betriebsausstattung
  computer: "0420"  # Büroeinrichtung
  software: "0420"
  fahrzeuge: "0350"  # Lkw
  pkw: "0320"  # Pkw

fremdleistungen:
  fremdleistung: "4400"  # Fremdleistungen
  montage: "4400"
  subunternehmer: "4400"
